### ISSUE TITLE
Show stacking status

### ISSUE THREAD

**Issue by friedger** [whoabuddy/sip015.xyz#22]
On login, show stacking status

Something similar to pool.friedger.de/members or pool registry
![image](https://user-images.githubusercontent.com/1449049/201164373-8c28bd9d-a221-41d6-ac73-aeb3d4d936dc.png)

**Comment by whoabuddy** [comment]
Great idea! Linking the [relevant code here](https://github.com/friedger/stacking/blob/main/packages/members/src/components/StackingStatus.js)
