### ISSUE TITLE
Bitcoin voters badge claim

### ISSUE THREAD

**Issue by Hero-Gamer** [whoabuddy/sip015.xyz#24]
Hi Jason, was talking to Jenny about Bitcoin voters' badge claim path on SIP015.xyz page. 
She thought if we can add a line below Method 1's "To vote No on 2.1..." line, that would say something like: 

"After you've voted via a Bitcoin transaction, click __this link__ to claim your "Voted" badge: 
Maybe this page would have intelligent way of detecting if he/she has voted, or just keep it simple not gated. 
cc: @radicleart

Something easy to deploy, not looking for advanced solution that will take too much effort. Completion date maybe sometimes next week? Then we can announce bitcoin voters can go back claim their badge if they voted previously.

Any thoughts?

**Comment by whoabuddy** [comment]
Yes issue #21 was based around adding a link for methods 1/2, I'm in favor of doing something simple.

@radicleart is there a page we can link to, or how does that interact with your flow?
